/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventocab.Items;

import inventocab.Models.ItemsInfoModel;
import inventocab.Models.ReturnInfoModel;
import inventocab.Models.others.ItemImageModel;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import raven.datetime.component.date.DatePicker;

 
public class returnpop extends javax.swing.JPanel {

    
    public String getDateReturned() {
    // Get the text from the dateRet field
    return DateRet.getText().trim();
}
    
    
    public ReturnInfoModel getData() {
    try {
        // Check if a date is selected in the dateReturned DatePicker
        Date dateReturnedData = dateReturned.isDateSelected() ? Date.valueOf(dateReturned.getSelectedDate()) : null;

        // If no date is selected, return null
        if (dateReturnedData == null) {
            JOptionPane.showMessageDialog(null, "Return date must be selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        // Create and return a ReturnInfoModel with only the return date
        ReturnInfoModel returnInfo = new ReturnInfoModel();
        returnInfo.setDateReturn(dateReturnedData);
        return returnInfo;

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred while retrieving the return date.", "Error", JOptionPane.ERROR_MESSAGE);
        return null;
    }
}
     public void setData (ReturnInfoModel data){
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
   
    // Check for null dates and format accordingly
    String dateReqStr = (data.getDateRequest() != null) ? dateFormat.format(data.getDateRequest()) : "";
    DateRet.setText(dateReqStr);
}
    
    
    
  
    private DatePicker dateReturned = new DatePicker();
    public returnpop() {
        initComponents();
        
         datePicker1.setCloseAfterSelected(true);
        datePicker1.setEditor(DateRet);
        
          dateReturned.setEditor(DateRet);
    
    dateReturned.setCloseAfterSelected(true);
    
   
    dateReturned.setDateFormat("yyyy-MM-dd");
    dateReturned.now();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker1 = new raven.datetime.component.date.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        DateRet = new javax.swing.JFormattedTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Return Date :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateRet, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateRet, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DateRet;
    private raven.datetime.component.date.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
